# Autogenerated wrapper script for XNNPACK_jll for aarch64-apple-darwin
export libxnnpack

using CPUInfo_jll
using PThreadPool_jll
JLLWrappers.@generate_wrapper_header("XNNPACK")
JLLWrappers.@declare_library_product(libxnnpack, "@rpath/libXNNPACK.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CPUInfo_jll, PThreadPool_jll)
    JLLWrappers.@init_library_product(
        libxnnpack,
        "lib/libXNNPACK.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
