# Autogenerated wrapper script for XNNPACK_jll for x86_64-w64-mingw32
export libxnnpack

using CPUInfo_jll
using PThreadPool_jll
JLLWrappers.@generate_wrapper_header("XNNPACK")
JLLWrappers.@declare_library_product(libxnnpack, "libXNNPACK.dll")
function __init__()
    JLLWrappers.@generate_init_header(CPUInfo_jll, PThreadPool_jll)
    JLLWrappers.@init_library_product(
        libxnnpack,
        "bin\\libXNNPACK.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
